### ISSUE TITLE
Hibernate Mod gets disabled after unplugging and reconnecting controller

### ISSUE THREAD

**Issue by Stangkrazy2** [swingflip/Hakchi-Hibernate-Mod#2]
Hibernate Mod seems to get disabled after unplugging and reconnecting the SNES Classic controller while on the SNES Classic menu screen or during gameplay. I was also unable to resume out of Hibernate or Standby after unplugging and reconnecting the controller while in either modes. I am running via USB-HOST

**Comment by swingflip** [comment]
What Kernel version are you running?
